node {
    def mvnHome

    stage('Preparation') {
        git 'https://github.com/eliasnogueira/selenium-java-lean-test-achitecture.git'
        mvnHome = tool 'M3'
    }

    stage('Build') {
        sh "'${mvnHome}/bin/mvn' clean package -DskipTests=true -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
    }

    stage('Test Execution') {
        try {
            sh "java -jar target/selenium-java-lean-test-achitecture-1.0.7.jar"
            sh "'${mvnHome}/bin/mvn' test -Pweb-execution -Dtarget=local -Dsuite=local -Dtestng.dtd.http=true -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
        } catch (Exception e) {
            currentBuild.result = 'FAILURE'
        } finally {
            junit '**/target/surefire-reports/TEST-*.xml'

            /*
             * Please read https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy
             * to allow Jenkins to load static files
             */
            publishHTML (target: [
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'target/surefire-reports',
                reportFiles: 'index.html',
                reportName: "TestNG Report"
            ])
        }
    }
}
